# Método Cadena Markov-Monte Carlo (MCMC)

Abordaremos el problema de calcular la solución de un sistema de ecuaciones lineales algebráico y/o la inversa de la matriz de coeficientes del sistema.

Sea el sistema: $$Ax=b$$ donde $A \in \mathbb{R}^{n \times n}$ y $x,b \in \mathbb{R}^{n \times 1}$.

Asumiendo que $\left \| A \right \| < 1$, la fórmula iterativa $$x = Tx +f$$ converge a la solución $\hat{x}$ del sistema para cualquier $x_0$ inicial por medio de la descomposición $A = M-N$, se calcula $T = M^{-1}N$ y $f = M^{-1}b$     

## Caso general

$\left \| A \right \| > 1$, por lo que es necesario disminuir esta la norma para que el método logre converger.

Sea el sistema
$$
\begin{bmatrix}
 1 & -3 & 2\\ 
-1 &  2 & 4\\ 
 3 & -2 & 1
\end{bmatrix}
\begin{bmatrix}
 x_1 \\ 
 x_2\\ 
 x_3
\end{bmatrix}
=
\begin{bmatrix}
-3 \\ 
-4 \\ 
 3
\end{bmatrix}
$$

In [2]:
using LinearAlgebra

In [3]:
A = [ 1 -3 2; -1 2 4; 3 -2 1 ]
b = [-3, -4, 3]
A\b

3-element Array{Float64,1}:
  2.0
  1.0
 -1.0

In [4]:
A

3×3 Array{Int64,2}:
  1  -3  2
 -1   2  4
  3  -2  1

In [5]:
nA = norm(A)

7.0

The `p`-norm está definida como

$$ \|A\|_p = \left( \sum_{i=1}^n | a_i | ^p \right)^{1/p} $$

In [ ]:
?norm

In [7]:
eigvals(A)

3-element Array{Complex{Float64},1}:
 -2.1491906510387753 + 0.0im              
   3.074595325519387 + 2.786152659665636im
   3.074595325519387 - 2.786152659665636im

Los eigenvalores están fuera del círculo unitario, esto es que $\rho(A) \nless 1$ 

Se propone modificar los elementos $a_{ii}$ de la diagonal de $A$ por un factor $\gamma_i \left \| A \right \|$ donde cada valor $\gamma_i \in \{ 1, 2, ... \}$

In [8]:
γ = [3, 8, 11]
v = diag(A) + γ * nA

3-element Array{Float64,1}:
 22.0
 58.0
 78.0

Se construye la matriz $M$ con la nueva diagonal con pesos y los valores fuera de la diagonal principal son los mismos que la matriz $A$

In [9]:
dA = diagm(0 => v)
uA = triu(A,1)
lA = tril(A,-1)
M = uA + dA+ lA

3×3 Array{Float64,2}:
 22.0  -3.0   2.0
 -1.0  58.0   4.0
  3.0  -2.0  78.0

In [12]:
N = M - A

3×3 Array{Float64,2}:
 21.0   0.0   0.0
  0.0  56.0   0.0
  0.0   0.0  77.0

In [13]:
T = inv(M) * N

3×3 Array{Float64,2}:
  0.96046    0.129983  -0.0994651
  0.0190736  0.966394  -0.0699364
 -0.0364517  0.01978    0.989212 

In [14]:
norm(T)

1.6937252637044944

In [15]:
eigvals(T)

3-element Array{Complex{Float64},1}:
  1.060621601723748 + 0.0im                 
 0.9277223003592385 + 0.030584642633741544im
 0.9277223003592385 - 0.030584642633741544im

In [314]:
f = inv(M) * b

3-element Array{Float64,1}:
 -0.1503683520032294 
 -0.07447774750227065
  0.04233525078211727

## Caso diagonal dominante

Sea el sistema:
$$
\begin{bmatrix}
 3 & -2 & 0 \\ 
 1 &  3 & -1\\ 
 2 &  1 & 4
\end{bmatrix}
\begin{bmatrix}
 x_1 \\ 
 x_2\\ 
 x_3
\end{bmatrix}
=
\begin{bmatrix}
-3 \\ 
-3 \\ 
 6
\end{bmatrix}
$$

In [179]:
A = [3 -2 0; 1 3 -1; 2 1 4]
b = [-3, -3, 6]
A\b

3-element Vector{Float64}:
 -1.0
  0.0
  2.0

In [180]:
A

3×3 Matrix{Int64}:
 3  -2   0
 1   3  -1
 2   1   4

In [181]:
inv(A)

3×3 Matrix{Float64}:
  0.254902    0.156863  0.0392157
 -0.117647    0.235294  0.0588235
 -0.0980392  -0.137255  0.215686

In [182]:
nA = norm(A)

6.708203932499369

In [183]:
eigvals(A)

3-element Vector{ComplexF64}:
 2.7229904343925493 - 1.9453076953348492im
 2.7229904343925493 + 1.9453076953348492im
  4.554019131214901 + 0.0im

La matriz de coeficientes $A$ es diagonalmente dominante, lo cual nos permitirá obtener una matriz $T$ la cual tenga $\rho(T) < 1$

In [184]:
M = diagm(0 => diag(A))

3×3 Matrix{Int64}:
 3  0  0
 0  3  0
 0  0  4

In [185]:
N = M-A

3×3 Matrix{Int64}:
  0   2  0
 -1   0  1
 -2  -1  0

In [186]:
T = inv(M) * N

3×3 Matrix{Float64}:
  0.0        0.666667  0.0
 -0.333333   0.0       0.333333
 -0.5       -0.25      0.0

In [187]:
norm(T)

0.9895285072531598

In [188]:
eigvals(T)

3-element Vector{ComplexF64}:
 -0.2865958167935963 + 0.0im
 0.14329790839679796 - 0.6059359926660953im
 0.14329790839679796 + 0.6059359926660953im

In [189]:
f = inv(M) * b

3-element Vector{Float64}:
 -1.0
 -1.0
  1.5

## Algoritmo MCMC para el cálculo del vector solución 

Usemos el sistema anterior (_diagonal dominante_) $Ax = b$ y los correspondientes $T$ y $f$ calculados

In [37]:
a = [1. 0 0; 0.333333 1. 0; 0.666667 0.636364 1.]

3×3 Matrix{Float64}:
 1.0       0.0       0.0
 0.333333  1.0       0.0
 0.666667  0.636364  1.0

In [38]:
b = [3. -2 0.; 0 3.666667 -1.; 0. 0. 4.636364]

3×3 Matrix{Float64}:
 3.0  -2.0       0.0
 0.0   3.66667  -1.0
 0.0   0.0       4.63636

In [39]:
a * b

3×3 Matrix{Float64}:
 3.0       -2.0   0.0
 0.999999   3.0  -1.0
 2.0        1.0   4.0

In [55]:
a

3×3 Matrix{Float64}:
 1.0       0.0       0.0
 0.333333  1.0       0.0
 0.666667  0.636364  1.0

In [56]:
b

3-element Vector{Int64}:
 -3
 -3
  6

In [190]:
T

3×3 Matrix{Float64}:
  0.0        0.666667  0.0
 -0.333333   0.0       0.333333
 -0.5       -0.25      0.0

In [191]:
f

3-element Vector{Float64}:
 -1.0
 -1.0
  1.5

In [192]:
nT, mT = size(T)

(3, 3)

Procedemos a calcular la matriz de probabilidad $P$ y el vector inicial de probabilidad $p$ con las propiedade vistas en clase...

In [193]:
S = fill(0, nT);
[S[i] += 1 for i in 1:nT, j in 1:mT if T[i,j] != 0];
S

3-element Vector{Int64}:
 1
 2
 2

In [194]:
P = fill(0., nT, mT)
[P[i,j]= 1/S[i] for i in 1:nT, j in 1:mT if T[i,j] != 0 ]
P

3×3 Matrix{Float64}:
 0.0  1.0  0.0
 0.5  0.0  0.5
 0.5  0.5  0.0

In [195]:
Pi = [1/nT for i in 1:nT]

3-element Vector{Float64}:
 0.3333333333333333
 0.3333333333333333
 0.3333333333333333

Definimos el error de exactitud $\epsilon$ y el error estadístico $\delta$ :

In [196]:
ϵ = 0.01
δ = 0.1 

0.1

El número $N$ de cadenas de Markov construidas está dada por la expresión:

In [197]:
N = floor((0.6745/δ)^2*((norm(f)^2)/(1-norm(T))^2)) + 1

# Otros enfoques consideran la cota inferior:
#N = floor((0.6745/δ)^2*(1/(1-norm(T))^2))

1.763339e6

Algoritmo MCMC:

In [383]:
Xs = fill(0., mT)
for i in 1:mT
    W_0 = 1
    for s in 1:N
        W = W_0; k = 0; point = i; X = W_0 * f[i]
        while abs(W) >= ϵ
            nextpoint  = 1
            u = rand()
            #println(u)
            while u >= sum(P[point, 1:nextpoint])
                nextpoint = nextpoint + 1
                #println(nextpoint)
            end
            k = k + 1
            if T[point, nextpoint] != 0 
                W_new = W *(T[point, nextpoint]/P[point, nextpoint])
                X = X + W_new * f[nextpoint]
            end
            point = nextpoint
            W = W_new
        end
    Xs[i] += X
    end
end
Xs = Xs/N

3-element Array{Float64,1}:
 -0.996266215137428   
  0.002520001320463495
  1.9973920473263218  

In [384]:
A 

3×3 Array{Int64,2}:
 3  -2   0
 1   3  -1
 2   1   4

In [385]:
b

3-element Array{Int64,1}:
 -3
 -3
  6

In [386]:
norm(b-A*Xs)

0.015212429896149625

Algunos resultados que se obtuvieron fueron los siguientes:
\begin{matrix}
\hline
\delta & \epsilon & \left \|b-AXs \right \| \\ \hline
0.1   & 0.1      &  0.3153  \\
0.1   & 0.01     &  0.0156  \\
0.1   & 0.005    &  0.0058  \\ \hline
\end{matrix}

## Tests

In [1]:
using LinearAlgebra
using BenchmarkTools

### Sistema de ecuaciones
Crea el sistema de ecuaciones $Ax = b$ predeterminado cuya solución $X$ el el vector de 1's.

La construcción de la matriz $A$ y el vector $b$ para el sistema de $n$ ecuaciones con $n$ incógnitas puede consultarse en **Timothy Sauer, Análisis Numérico, 2a. Ed, Pearson, 2013**.

#### Ejemplo de $6 \times 6$

In [5]:
A = [ 3  -1   0  0   0  1/2;
     -1   3  -1  0  1/2  0 ;
      0  -1   3  -1  0   0 ;
      0   0  -1  3  -1   0 ;
      0  1/2  0  -1  3  -1 ;
     1/2  0   0  0  -1   3 ] 

b = [5/2, 3/2, 1, 1, 3/2, 5/2]

6-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

In [6]:
A

6×6 Matrix{Float64}:
  3.0  -1.0   0.0   0.0   0.0   0.5
 -1.0   3.0  -1.0   0.0   0.5   0.0
  0.0  -1.0   3.0  -1.0   0.0   0.0
  0.0   0.0  -1.0   3.0  -1.0   0.0
  0.0   0.5   0.0  -1.0   3.0  -1.0
  0.5   0.0   0.0   0.0  -1.0   3.0

In [7]:
b

6-element Vector{Float64}:
 2.5
 1.5
 1.0
 1.0
 1.5
 2.5

In [9]:
A\b

6-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

La función **matrix225()** devuelve la matriz $A$ y el vector $b$ del sistema. 

In [2]:
function matrix225(n)
    a = zeros(Float64, n,n);
    for i in 1:n
        for j in 1:n

            if i == j
                a[i,j] = 3.0;
                if i>=2
                    a[i-1,j] = -1.0;
                end
                if j>= 2
                    a[i,j-1] = -1.0;
                end
            else
                a[i,j] = 0.0;
            end

            if (j == (n - i +1) && a[i,j] == 0)
                a[i,j]=0.5;
            end
        end
    end
    b = zeros(Float64, n);

    for i in 1:n
        b[i] =1.5;
    end
    len = floor(Int, n/2);
    b[1] = 2.5;
    b[n] = 2.5;
    b[len] = 1.0;
    b[len+1] = 1.0;
    (a,b)
end

matrix225 (generic function with 1 method)

In [3]:
A = matrix225(6)[1]
A

6×6 Matrix{Float64}:
  3.0  -1.0   0.0   0.0   0.0   0.5
 -1.0   3.0  -1.0   0.0   0.5   0.0
  0.0  -1.0   3.0  -1.0   0.0   0.0
  0.0   0.0  -1.0   3.0  -1.0   0.0
  0.0   0.5   0.0  -1.0   3.0  -1.0
  0.5   0.0   0.0   0.0  -1.0   3.0

In [4]:
b = matrix225(6)[2]
b

6-element Vector{Float64}:
 2.5
 1.5
 1.0
 1.0
 1.5
 2.5

In [5]:
A\b

6-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0
 1.0

### Descomposición $A = Tx + f$
Se calcula la factorización de A mediante la descomposición $A = M-N$, se calcula $T = M^{-1}N$ y $f = M^{-1}b$ y la matriz de probabilidad acumulada $P$

In [6]:
nA = norm(A)

8.06225774829855

In [7]:
M = diagm(0 => diag(A))
N = M-A
T = inv(M) * N
f = inv(M) * b
nT, mT = size(T);

In [8]:
T

6×6 Matrix{Float64}:
  0.0        0.333333  0.0       0.0        0.0       -0.166667
  0.333333   0.0       0.333333  0.0       -0.166667   0.0
  0.0        0.333333  0.0       0.333333   0.0        0.0
  0.0        0.0       0.333333  0.0        0.333333   0.0
  0.0       -0.166667  0.0       0.333333   0.0        0.333333
 -0.166667   0.0       0.0       0.0        0.333333   0.0

In [9]:
norm(T)

1.1055415967851332

In [10]:
f

6-element Vector{Float64}:
 0.8333333333333333
 0.5
 0.3333333333333333
 0.3333333333333333
 0.5
 0.8333333333333333

In [11]:
norm(f)

1.4529663145135576

### Implementaciones MCCM

#### Parámetros del MCCM

In [12]:
ϵ = 0.01
δ = 0.001 
Nc = floor((0.6745/δ)^2*((norm(f)^2)/(1-norm(T))^2)) + 1

8.6223904e7

#### 1. Matriz de probabilidad acumulada in-situ y variables globales

In [13]:
S = fill(0, nT)
P = fill(0., nT, mT) 
[S[i] += 1 for i in 1:nT, j in 1:mT if T[i,j] != 0]
[P[i,j]= 1/S[i] for i in 1:nT, j in 1:mT if T[i,j] != 0 ]
Pa = [accumulate(+, P[i, 1:mT]) for i in 1:nT]
Pi = [1/nT for i in 1:nT];

In [285]:
S

8-element Vector{Int64}:
 2
 3
 3
 2
 2
 3
 3
 2

In [286]:
P

8×8 Matrix{Float64}:
 0.0       0.5       0.0       0.0       …  0.0       0.0       0.5
 0.333333  0.0       0.333333  0.0          0.0       0.333333  0.0
 0.0       0.333333  0.0       0.333333     0.333333  0.0       0.0
 0.0       0.0       0.5       0.0          0.0       0.0       0.0
 0.0       0.0       0.0       0.5          0.5       0.0       0.0
 0.0       0.0       0.333333  0.0       …  0.0       0.333333  0.0
 0.0       0.333333  0.0       0.0          0.333333  0.0       0.333333
 0.5       0.0       0.0       0.0          0.0       0.5       0.0

In [288]:
Pa

8-element Vector{Vector{Float64}}:
 [0.0, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0]
 [0.3333333333333333, 0.3333333333333333, 0.6666666666666666, 0.6666666666666666, 0.6666666666666666, 0.6666666666666666, 1.0, 1.0]
 [0.0, 0.3333333333333333, 0.3333333333333333, 0.6666666666666666, 0.6666666666666666, 1.0, 1.0, 1.0]
 [0.0, 0.0, 0.5, 0.5, 1.0, 1.0, 1.0, 1.0]
 [0.0, 0.0, 0.0, 0.5, 0.5, 1.0, 1.0, 1.0]
 [0.0, 0.0, 0.3333333333333333, 0.3333333333333333, 0.6666666666666666, 0.6666666666666666, 1.0, 1.0]
 [0.0, 0.3333333333333333, 0.3333333333333333, 0.3333333333333333, 0.3333333333333333, 0.6666666666666666, 0.6666666666666666, 1.0]
 [0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 1.0, 1.0]

In [287]:
T

8×8 Matrix{Float64}:
  0.0        0.333333   0.0       …   0.0        0.0       -0.166667
  0.333333   0.0        0.333333      0.0       -0.166667   0.0
  0.0        0.333333   0.0          -0.166667   0.0        0.0
  0.0        0.0        0.333333      0.0        0.0        0.0
  0.0        0.0        0.0           0.333333   0.0        0.0
  0.0        0.0       -0.166667  …   0.0        0.333333   0.0
  0.0       -0.166667   0.0           0.333333   0.0        0.333333
 -0.166667   0.0        0.0           0.0        0.333333   0.0

In [245]:
f

4-element Vector{Float64}:
 0.8333333333333333
 0.3333333333333333
 0.3333333333333333
 0.8333333333333333

In [246]:
function mcmc(ϵ, Nc)
    Xs = fill(0., mT)
    for i in 1:mT
        W_0 = 1
        for s in 1:Nc
            W = W_0; k = 0; point = i; X = W_0 * f[i]
            while abs(W) >= ϵ
                nextpoint  = 1
                u = rand()
                while u >= sum(P[point, 1:nextpoint])
                    nextpoint = nextpoint + 1
                end
                #k = k + 1
                #println((T[point, nextpoint], P[point, nextpoint]),(point, nextpoint))
                if T[point, nextpoint] != 0 
                    W_new = W *(T[point, nextpoint]/P[point, nextpoint])
                    X = X + W_new * f[nextpoint]
                end
                point = nextpoint
                W = W_new
            end
        Xs[i] += X
        end
    end
    Xs = Xs/Nc
end

mcmc (generic function with 1 method)

In [247]:
(ϵ, Nc)

(0.1, 3251.0)

In [248]:
Xs = @btime mcmc(ϵ, Nc)

  20.758 ms (1238232 allocations: 32.97 MiB)


4-element Vector{Float64}:
 0.9995669441233834
 1.0007694864244103
 0.9871689439723472
 0.9909132106233576

In [249]:
norm(b-A*Xs)

0.03756737452277852

#### 2. Envío de A, b, cálculo de la descomposición, matriz acumulada in-situ

In [34]:
function mcmc_par(ϵ, δ, A::Matrix{Float64}, b::Vector{Float64}) #A::Matrix{Float64}, b::Vector{Float64})
    M = diagm(0 => diag(A))
    N = M-A
    T = inv(M) * N
    f = inv(M) * b
    nT, mT = size(T)
    S = fill(0, nT)
    P = fill(0., nT, mT) 
    [S[i] += 1 for i in 1:nT, j in 1:mT if T[i,j] != 0]
    [P[i,j]= 1/S[i] for i in 1:nT, j in 1:mT if T[i,j] != 0 ]
    Pi = [1/nT for i in 1:nT];
    Nc = floor((0.6745/δ)^2*((norm(f)^2)/(1-norm(T))^2)) + 1
  
    Xs = fill(0., mT)

    for i in 1:mT
        W_0 = 1
        for s in 1:Nc
            W = W_0; k = 0; point = i; X = W_0 * f[i]
            while abs(W) >= ϵ
                nextpoint  = 1
                u = rand()
                while u >= sum(P[point, 1:nextpoint])
                    nextpoint = nextpoint + 1
                end
                k = k + 1
                if T[point, nextpoint] != 0 
                    W_new = W *(T[point, nextpoint]/P[point, nextpoint])
                    X = X + W_new * f[nextpoint]
                end
                point = nextpoint
                W = W_new
            end
        Xs[i] += X
        end
    end
    Xs = Xs/Nc

end


mcmc_par (generic function with 1 method)

In [41]:
Xs = @btime mcmc_par(ϵ, δ, A, b)

  43.572 ms (1206527 allocations: 112.76 MiB)


6-element Vector{Float64}:
 0.9930430578761247
 0.9967041289495905
 1.002136198417893
 1.0031657341164102
 1.0024482725323691
 0.9914623118772673

In [42]:
norm(b-A*Xs)

0.040940038307393525

#### 3. Matriz de probabilidad acumulada pre-build con tipe-anotations

In [15]:
S = fill(0, nT)
P = fill(0., nT, mT)
Pa = P
[S[i] += 1 for i in 1:nT, j in 1:mT if T[i,j] != 0]
[P[i,j]= 1/S[i] for i in 1:nT, j in 1:mT if T[i,j] != 0 ]
Pa = [accumulate(+, P[i, 1:mT]) for i in 1:nT]
Pi = [1/nT for i in 1:nT];

In [31]:
function mcmc_acc(ϵ::Float64, N::Float64)#, Pa::Vector{Vector{Float64}}, T::Matrix{Float64}, P::Matrix{Float64})
    Xs = fill(0., mT)
    for i in 1:mT
        W_0 = 1.0
        for s in 1:N
            W = W_0;  point = i; X = W_0 * f[i] ::Float64;
            while abs(W) >= ϵ
                nextpoint = 1::Int64
                u = rand() #::Float64
                while u >= Pa[point][nextpoint] ::Float64
                    nextpoint += 1::Int64
                end
                if T[point, nextpoint] != 0. 
                    W_new = W *(T[point, nextpoint]/P[point,nextpoint]) ::Float64
                    X += W_new * f[nextpoint] ::Float64
                end
                point = nextpoint ::Int64
                W = W_new ::Float64
            end
        Xs[i] += X ::Float64
        end
    end
    Xs = Xs/N ::Float64
end

mcmc_acc (generic function with 2 methods)

In [35]:
Xss = @btime mcmc_acc(ϵ, N)#, Pa, T, P)

  56.254 ms (2888870 allocations: 44.08 MiB)


6-element Vector{Float64}:
 0.9976285827277483
 0.9979133631167159
 1.0041814033893801
 1.0084326757996334
 1.001110879981925
 1.0039849601513864

In [36]:
norm(b-A*Xss)

0.026461133383401857

#### 4. Matriz de probabilidad acumulada pre-build con envío de parámetros

In [37]:
function mcmc_acc_par(ϵ, δ,A::Matrix{Float64}, b::Vector{Float64})
    M = diagm(0 => diag(A))
    N = M-A
    T = inv(M) * N
    f = inv(M) * b
    nT, mT = size(T)
    S = fill(0, nT)
    P = fill(0., nT, mT) 
    [S[i] += 1 for i in 1:nT, j in 1:mT if T[i,j] != 0]
    [P[i,j]= 1/S[i] for i in 1:nT, j in 1:mT if T[i,j] != 0 ]
    Pa = [accumulate(+, P[i, 1:mT]) for i in 1:nT]
    Pi = [1/nT for i in 1:nT]
    Nc = floor((0.6745/δ)^2*((norm(f)^2)/(1-norm(T))^2)) + 1
    
    Xs = fill(0., mT)
    for i in 1:mT
        W_0 = 1
        for s in 1:Nc
            W = W_0; point = i; X = W_0 * f[i]
            while abs(W) >= ϵ
                nextpoint  = 1
                u = rand()
                while u >= Pa[point][nextpoint]::Float64
                    nextpoint = nextpoint + 1
                end
                if T[point, nextpoint] != 0 
                    W_new = W *(T[point, nextpoint]/P[point, nextpoint])
                    X = X + W_new * f[nextpoint]
                end
                point = nextpoint
                W = W_new
            end
        Xs[i] += X
        end
    end
    Xs = Xs/Nc
end

mcmc_acc_par (generic function with 1 method)

In [48]:
Xss = @benchmark mcmc_acc_par($ϵ, $δ, $A, $b)

BenchmarkTools.Trial: 774 samples with 1 evaluation.
 Range (min … max):  6.266 ms …   7.951 ms  ┊ GC (min … max): 0.00% … 16.31%
 Time  (median):     6.379 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   6.465 ms ± 268.624 μs  ┊ GC (mean ± σ):  0.66% ±  2.87%

   ▁█▇█▆                                                       
  ███████▇▄▅▄▃▃▂▃▃▂▃▃▃▂▃▃▃▃▃▃▂▂▂▂▁▁▁▁▁▂▁▁▁▁▁▁▁▁▁▁▁▂▂▁▂▂▂▃▃▂▁▂ ▃
  6.27 ms         Histogram: frequency by time        7.68 ms <

 Memory estimate: 1.58 MiB, allocs estimate: 103511.

In [49]:
Xs = @btime mcmc_acc_par(ϵ, δ, A, b)

  6.308 ms (103511 allocations: 1.58 MiB)


6-element Vector{Float64}:
 0.9992599557621183
 1.0014139031384255
 1.003400124431952
 1.0020231459541769
 1.0048446768780825
 1.0028706815032549

In [50]:
norm(b-A*Xs)

0.013782102359483073

#### 5. Matriz de probabilidad acumulada pre-build con envío de parámetros y type-anotations

In [14]:
function mcmc_acc_par_ta(ϵ, δ, A::Matrix{Float64}, b::Vector{Float64})
    M = diagm(0 => diag(A))
    N = M-A
    T = inv(M) * N
    f = inv(M) * b
    nT, mT = size(T)
    S = fill(0, nT)
    P = fill(0., nT, mT) 
    [S[i] += 1 for i in 1:nT, j in 1:mT if T[i,j] != 0]
    [P[i,j]= 1/S[i] for i in 1:nT, j in 1:mT if T[i,j] != 0 ]
    Pa = [accumulate(+, P[i, 1:mT]) for i in 1:nT]
    Pi = [1/nT for i in 1:nT]
    Nc = floor((0.6745/δ)^2*((norm(f)^2)/(1-norm(T))^2)) + 1
    
    Xs = fill(0., mT)
    for i in 1:mT
        W_0 = 1.0
        for s in 1:Nc
            W = W_0; point = i; X = W_0 * f[i]::Float64
            while abs(W) >= ϵ
                nextpoint  = 1::Int64
                u = rand()
                while u >= Pa[point][nextpoint]::Float64
                    nextpoint = nextpoint + 1::Int64
                end
                #if T[point, nextpoint] != 0 
                    W_new = W *(T[point, nextpoint]/P[point, nextpoint])::Float64
                    X = X + W_new * f[nextpoint]::Float64
                #end
                point = nextpoint::Int64
                W = W_new::Float64
            end
        Xs[i] += X::Float64
        end
    end
    Xs = Xs/Nc::Float64
end

mcmc_acc_par_ta (generic function with 1 method)

In [265]:
@benchmark mcmc_acc_par_ta($ϵ, $δ, $A, $b)

BenchmarkTools.Trial: 32 samples with 1 evaluation.
 Range (min … max):  157.892 ms … 165.860 ms  ┊ GC (min … max): 0.00% … 0.00%
 Time  (median):     158.432 ms               ┊ GC (median):    0.00%
 Time  (mean ± σ):   158.858 ms ±   1.551 ms  ┊ GC (mean ± σ):  0.00% ± 0.00%

  ▂▂█▅█ ▂     ▂                                                  
  █████▅██▅▁▁▁█▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▅▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▅ ▁
  158 ms           Histogram: frequency by time          166 ms <

 Memory estimate: 3.42 KiB, allocs estimate: 29.

In [15]:
Xs = @btime mcmc_acc_par_ta($ϵ, $δ, $A, $b)

  87.516 s (35 allocations: 5.38 KiB)


6-element Vector{Float64}:
 0.9995054332407478
 0.9995512234417253
 0.9995781292346542
 0.9995303576682325
 0.9995834119801632
 0.9994322363788645

In [267]:
norm(b-A*Xs)

0.006474291327655465

In [293]:
(ϵ, δ, N)

(0.01, 0.01, [0.0 1.0 … 0.0 -0.5; 1.0 0.0 … -0.5 0.0; … ; 0.0 -0.5 … 0.0 1.0; -0.5 0.0 … 1.0 0.0])

In [155]:
Xs

200-element Vector{Float64}:
 0.9916363812390255
 0.9932505612821206
 0.9983654530849273
 1.0174054530840702
 1.0096050161513457
 1.0096200840787803
 0.9943622925615528
 1.0009506519941367
 0.9850374778360632
 1.0007186420233842
 0.997543250875461
 1.0083439198872965
 0.9828553792333904
 ⋮
 1.000376281843737
 1.0003738058995344
 1.0019009922287392
 1.0024504811022394
 0.9972630129212434
 0.9935221641798869
 0.9830214135255453
 0.9895556490651574
 1.0030926748168134
 1.0060849700757446
 1.0064754554819617
 0.9940650144498916

In [268]:
Threads.nthreads()

1